### ISSUE TITLE
[FEATURE] Do away with `ListColumn` index in favor of something faster

### ISSUE THREAD

**Issue by seyuboglu** [HazyResearch/meerkat#117]
Meerkat imposes a `ListColumn` index on all `DataPanel`. In many cases, this is the slowest column in the dp and it bottlenecks performance, since all the other columns are based on numpy, pandas or torch. 
We should do away with the index column in favor of something else...

It's also worth thinking about what purpose the "index" column serves in the DataPanel. Its not clear to me that it's providing anything important (though I may be missing something). It seems that its main purpose is to provide some sort of unique "id" for every row in the DataPanel, but I don't think this is something we should impose on the DataPanel. That being said, I see the appeal of being able to specify some "id" columns that have some special properties (e.g. always get carried from one dp to the next when indexing). 

I propose doing away with this single "index" column design in favor of a new design inspired by the idea of indexes in database management systems:
- We can mark any column in a `DataPanel`as an index. For example: 
```python
mimic_dp = ...
mimic_dp.set_index(column="dicom_id")
```
- Rows can then be looked up by that index in a shorthand form:
```python
row = mimic_dp.idx["dicom_id", "id_e324198"]
sub_dp =  mimic_dp.idx["dicom_id", ["id_e324198", "id_e1236493",]]
```
- Under the hood, columns can specify fast implementations of indexes. By default columns will implement the naive slow O(n) index:
```python
def idx(self, index_name, index):
    return self[self[index_name] == index]
```
but columns can override this with faster implementations, _e.g._ based on a `pandas.Index` object which is backed by a Cython dict, so provides O(1) lookups (https://pandas.pydata.org/pandas-docs/stable/development/internals.html).

**Comment by seyuboglu** [comment]
@krandiash @ad12

**Comment by krandiash** [comment]
Good proposal: the main reason that index existed in RG is as a uuid that could be carried and modified through transformations of an example (eg in data augmentation). You can think of it as a quick and easy way to preserve provenance at the example level.

I think your suggestion goes beyond what that did (and I agree with the premise of your argument). Any time that a string uuid is needed I think the downstream user (RG) can be responsible for it (and can mark it an index).

**Comment by seyuboglu** [comment]
An `index` column is no longer added automatically as of #208
