### ISSUE TITLE
[BUG] typing doesn't have Literal

### ISSUE THREAD

**Issue by duguyue100** [HazyResearch/meerkat#283]
**Describe the bug**

https://github.com/HazyResearch/meerkat/blob/main/meerkat/interactive/app/src/lib/component/abstract.py#L7

In this line, the `Literal` type is imported from `typing` but `typing` doesn't have `Literal`, it should be `typing_extensions`.
This will result an import error.

**Comment by krandiash** [comment]
Thanks for the bug report, #286 should address this when it's merged into main. I suggest using Py 3.8+ in the meantime

**Comment by krandiash** [comment]
Merged into `main`, you should be able to use it right now with a direct clone + install from `main`. Otherwise this will be in our next release (which will go out in the next 24 hours).

**Comment by ad12** [comment]
we pushed up the latest patch, which includes this fix:
 
```bash
pip install --upgrade meerkat-ml
```

**Comment by duguyue100** [comment]
Thanks for fixing this!  We will definitely try in our next release cycle.
