### ISSUE TITLE
[BUG] No file found when running demo script

### ISSUE THREAD

**Issue by jdunnmon** [HazyResearch/meerkat#285]
**Describe the bug**
No such file or directory found when trying to run demos.

**To Reproduce**
Steps and code snippet that reproduce the behavior:

`mk demo --run tutorial-image-gallery --api-port 8890`

Include any relevant screenshots.

![image](https://user-images.githubusercontent.com/14251104/222780741-d74f1ba3-ce47-4fbe-9c2d-d683f350025c.png)

**Expected behavior**

Expect demo to run on port 8890

**System Information**
 - OS: Ubuntu

**Comment by krandiash** [comment]
It sounds like there's an issue with downloading `imagenette`. Does running `mk.get("imagenette", version="160px")` work for you? You can also try deleting `/home/jdunnmon/.meerkat/datasets/imagenette/160px/` and retry (let us know if that doesn't work).

**Comment by jdunnmon** [comment]
Yeah, running the command above manually works.  I think there is an issue with the `mk demo` command, in that it uses the full version not the 160 px version.

**Comment by krandiash** [comment]
That's weird, the demo file itself has 
```
df = mk.get("imagenette", version="160px")
```
for the `tutorial-image-gallery` demo. You can try adding the `--copy` flag to `mk demo` and then looking at the script (and try running this copied script with `mk run`)
