### ISSUE TITLE
[BUG] Partial dataset download breaks `mk.datasets.get`

### ISSUE THREAD

**Issue by sluijs** [HazyResearch/meerkat#311]
**Describe the bug**
If a download of a dataset gets interrupted, the `mk.datasets.get(...)` function will fail on retries: 

```
FileNotFoundError: [Errno 2] No such file or directory: '~/.meerkat/datasets/imagenette/full/imagenette2/noisy_imagenette.csv
``` 

**To Reproduce**
Interrupt `mk.dataset.get("imagenette")` and run it again.

**System Information**
 - OS: Ubuntu 20.04

**Comment by krandiash** [comment]
Thanks for reporting, taking a look, will update you when a fix is in.

**Comment by krandiash** [comment]
@sluijs Could you try running `mk.dataset.get('imagenette', download_mode='force')` and let me know if that succeeds for you?

**Comment by krandiash** [comment]
@sluijs let me know if that works for you
