### ISSUE TITLE
Issue on page /index.html - The link to blogpost doesn't work

### ISSUE THREAD

**Issue by parulnith** [HazyResearch/meerkat#313]
The link to the blog post on the documentation's index page doesn't work

**Comment by krandiash** [comment]
Hm I was able to load it, would you be able to try again? Perhaps it was a temporary browser issue?

**Comment by parulnith** [comment]
@krandiash weird, it still doesn't work for me. The link to the blogpost on the documentation page is https://hazyresearch.stanford.edu/blog/meerkat while if I go directly to the blog, the link to this specific article is  - http://meerkat.wiki/blog. Attached a gif also.
![Untitled](https://user-images.githubusercontent.com/16894695/228413605-2c6cfd38-6530-4d2b-9841-454804a5ac0b.gif)

**Comment by krandiash** [comment]
Ah, thanks for clarifying, looks like the link is wrong and should be https://hazyresearch.stanford.edu/blog/2023-03-01-meerkat, appreciate it!
