### ISSUE TITLE
GUI not showing

### ISSUE THREAD

**Issue by fepegar** [HazyResearch/meerkat#359]
Hi! This project looks great, but I haven't been able to make things work. I've tried showing a data frame on a notebook, as in the tutorials/demos, and also the command `mk demo tutorial-image-gallery --copy`. In both cases (the notebook and the browser), all I see is an image with the meerkat logo, not the data frame or the gallery that I was expecting.

![image](https://github.com/HazyResearch/meerkat/assets/12688084/291aca01-d527-4206-8b6b-dda27405866f)

Might I be doing something obviously wrong?

**Comment by ad12** [comment]
@fepegar thanks for the note! could you share a few specifics about your setup:
- OS
  - if you are using windows, you may have to use the windows subsystem for linux
- Is the program running on remote or local machine?
- is there any error on the browser console? on chrome you can access this via `View -> Developer -> Javascript Console`

## Possible solutions
### Remote machines require port forwarding
If you are using a remote machine, you'll need to forward the frontend and api ports (8000 and 5000 by default)

### Change the api/frontend ports
you can change the ports you are forwarding with `mk demo tutorial-image-gallery --api-port XXXX --frontend-port XXXX`

**Comment by fepegar** [comment]
Hi, @ad12. Thanks for your quick response. I was trying on Linux, remotely. I did forward the ports: I guess that's why I could see the logo.

I did quickly check the browser console and I think something was off. Let me confirm that and also try things locally.

**Comment by fepegar** [comment]
The browser issue was my mistake: I was going to `http://localhost:8001/` instead of `http://localhost:8001/?id=gallery`.

I'll try the notebook again. I guess I don't need to forward ports for that, right?

**Comment by ad12** [comment]
You will need to forward the api/frontend ports from the notebook as well. By default the ports are `5000` and `8000`
